Repository sous-chefs/nodejs, pull requests merged in 2020-10, with the labels that each got.

#215 Add ability to set NODE_ENV for npm_package
  CHANGELOG.md
  README.md
  resources/npm_package.rb
  test/cookbooks/test/recipes/resource.rb
  test/cookbooks/test/templates/package.json
  test/integration/binary/default.rb
  test/integration/package/default.rb
  test/integration/source/default.rb
Labels: Priority: Medium, Release: Minor

#216 Add npx as binary for binary & source installs
  CHANGELOG.md
  recipes/nodejs_from_binary.rb
  test/integration/binary/default.rb
  test/integration/source/default.rb
Labels: Priority: Low, Release: Minor

#220 Npm registry url
  CHANGELOG.md
  libraries/nodejs_helper.rb
  recipes/npm_packages.rb
  resources/npm_package.rb
  test/cookbooks/test/recipes/package.rb
  test/cookbooks/test/recipes/resource.rb
  test/cookbooks/test/recipes/source_iojs.rb
  test/integration/package/default.rb
Labels: Release: Minor

#194 Add live_stream parameter to npm_package execution
  resources/npm_package.rb
Labels: Feature Request, Good First Issue, Priority: Medium, Release: Minor

#223 Chocolatey install method
  CHANGELOG.md
  README.md
  attributes/default.rb
  kitchen.yml
  metadata.rb
  recipes/nodejs_from_chocolatey.rb
  test/cookbooks/test/recipes/chocolatey.rb
  test/cookbooks/test/recipes/resource_win.rb
  test/integration/chocolatey/default.rb
Labels: Release: Minor

#225 Add the auto_update option to the npm_package resource.
  CHANGELOG.md
  README.md
  resources/npm_package.rb
  test/cookbooks/test/recipes/resource.rb
  test/integration/package/default.rb
Labels: Feature Request, Release: Minor

#226 Add rspec tests for the library methods
  CHANGELOG.md
  libraries/nodejs_helper.rb
  spec/rspec_helper.rb
  spec/unit/library/helper_spec.rb
Labels: Release: Patch

#229 Changelog update #patch
  CHANGELOG.md
  spec/unit/library/helper_spec.rb
Labels: Release: Patch

#231 Enable dokken-fedora-latest test suite #patch
  .github/workflows/ci.yml
  attributes/repo.rb
  recipes/repo.rb
Labels: Release: Patch, hacktoberfest, hacktoberfest-accepted
